#! /bin/sh

bspc config border_width                5
bspc config window_gap                  5
bspc config bottom_padding              30

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc monitor -d Desktop-1 Desktop-2 Desktop-3 Desktop-4 Desktop-5 Desktop-6 Desktop-7
bspc desktop ^2 -l monocle

bspc config focused_border_color        '#004790'
bspc config normal_border_color         '#27AE60'
bspc config presel_feedback_color       '#004790'

bspc rule -a gcolor2 state=floating center=on
bspc rule -a lxappearance state=floating center=on
bspc rule -a file-roller state=floating center=on
bspc rule -a chromium desktop=^2
bspc rule -a Wrapper-1.0 state=floating center=off border=off
bspc rule -a Screenruler border=off
bspc rule -a Xfce4-taskmanager state=floating center=on 
bspc rule -a discord desktop=^1
bspc rule -a Quasselclient desktop=^3
bspc rule -a Xfce4-terminal desktop=^4
bspc rule -a Gitter desktop=^7
bspc rule -a Thunar desktop=^5
bspc rule -a Geany desktop=^5
bspc rule -a Gimp-2.8 desktop=^6 state=floating follow=on
bspc rule -a Hexchat desktop=^3
bspc rule -a Blender desktop=^5
bspc rule -a Minitube desktop=^5

bspc config external_rules_command ~/.config/bspwm/pseudo_automatic_mode

xset -b &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
sxhkd &
dunst &
xfce4-power-manager &
xfce4-panel -d &
thunar --daemon &
pulseaudio --start &
compton -b &
conky &
redshift-gtk -c ~/.config/redshift/redshift.conf &
setxkbmap -model pc104 -layout us,ru -variant us -option grp:alt_shift_toggle &
/usr/libexec/polkit-gnome-authentication-agent-1 &
chromium &
/home/benjamin/Downloads/DiscordCanary/DiscordCanary &
quasselclient &
xfce4-terminal &
connman-ui-gtk &
